version: "2"

submodules:
  include: all
  recursive: true
  
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - doxygen
    - graphviz
  jobs:
    pre_build:
      - doxygen docs/Doxyfile

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
